### ISSUE TITLE
v2.0 crashes

### ISSUE THREAD

**Issue by 0Chris0** [Modding-Legacy/Aether-Legacy#276]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.4-122.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 1/28/18 7:33 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Aether Legacy (aether_legacy)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/player/AdvancementEvent
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:81)
	at com.legacy.aether.ServerProxy.registerEvent(ServerProxy.java:30)
	at com.legacy.aether.player.capability.PlayerAetherManager.initialization(PlayerAetherManager.java:24)
	at com.legacy.aether.Aether.initialization(Aether.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:719)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:348)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.entity.player.AdvancementEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 48 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 826923968 bytes (788 MB) / 2164260864 bytes (2064 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2512 Optifine OptiFine_1.12.2_HD_U_C7 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version              | Source                                      | Signature                                |
	|:----- |:----------------- |:-------------------- |:------------------------------------------- |:---------------------------------------- |
	| UCHI  | minecraft         | 1.12.2               | minecraft.jar                               | None                                     |
	| UCHI  | mcp               | 9.42                 | minecraft.jar                               | None                                     |
	| UCHI  | FML               | 8.0.99.99            | forge-1.12.2-14.23.0.2512.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | forge             | 14.23.0.2512         | forge-1.12.2-14.23.0.2512.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | mercurius_updater | 1.0                  | MercuriusUpdater-1.12.2.jar                 | None                                     |
	| UCHE  | aether_legacy     | v1.0                 | aether_legacy-1.12.2-1.0.jar                | None                                     |
	| UCHI  | quark             | r1.4-122             | Quark-r1.4-122.jar                          | None                                     |
	| UCHI  | autoreglib        | 1.3-15               | AutoRegLib-1.3-15.jar                       | None                                     |
	| UCHI  | grimpack          | 5.2.12.78            | Grim+Pack-1.12.2-5.2.12.78.jar              | None                                     |
	| UCHI  | ichunutil         | 7.1.4                | iChunUtil-1.12.2-7.1.4.jar                  | None                                     |
	| UCHI  | jei               | 4.8.5.133            | jei_1.12.2-4.8.5.133.jar                    | None                                     |
	| UCHI  | lycanitesmobs     | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
	| UCHI  | arcticmobs        | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
	| UCHI  | demonmobs         | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
	| UCHI  | desertmobs        | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
	| UCHI  | elementalmobs     | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
	| UCHI  | forestmobs        | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
	| UCHI  | freshwatermobs    | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
	| UCHI  | infernomobs       | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
	| UCHI  | junglemobs        | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
	| UCHI  | mountainmobs      | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
	| UCHI  | plainsmobs        | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
	| UCHI  | saltwatermobs     | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
	| UCHI  | shadowmobs        | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
	| UCHI  | swampmobs         | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
	| UCHI  | metamorph         | 1.1.4                | metamorph-1.1.4-1.12.1.jar                  | None                                     |
	| UCHI  | primitivemobs     | 1.1.1                | Primitive-Mobs-Mod-1.12.2.jar               | None                                     |
	| UCHI  | spartanweaponry   | beta 1.1.2           | SpartanWeaponry-1.12.2-beta-1.1.2.jar       | None                                     |
	| UCHI  | twilightforest    | 3.1.128              | twilightforest-1.12.2-3.1.128-universal.jar | None                                     |
	| UCHI  | worldedit         | 6.1.8                | worldedit-forge-mc1.12-6.1.8-dist.jar       | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.4-122.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.1008' Renderer: 'AMD Radeon HD 5450'
	Grim Pack loaded parts: 
	= Grim Core { Loaded }
		~ Enable aluminum subpart { Enabled }
		~ Enable coal subpart { Enabled }
		~ Enable graphite subpart { Enabled }
		~ Enable iron subpart { Enabled }
		~ Enable rubber subpart { Enabled }
		~ Enable steel subpart { Enabled }
	= Grim Cuisine { Loaded }
		~ Enable SubPart chocolate { Enabled }
		~ Enable SubPart dairy { Enabled }
		~ Enable SubPart dragon fruit { Enabled }
		~ Enable SubPart health { Enabled }
		~ Enable SubPart pie { Enabled }
		~ Enable SubPart soda { Enabled }
	= Grim Decor { Loaded }
		~ Enable SubPart alarm { Enabled }
		~ Enable SubPart cages { Enabled }
		~ Enable SubPart calendar { Enabled }
		~ Enable SubPart colorizer { Enabled }
		~ Enable SubPart decorations { Enabled }
		~ Enable SubPart fireplaces { Enabled }
		~ Enable SubPart flat item frame { Enabled }
		~ Enable SubPart fluro { Enabled }
		~ Enable SubPart frames { Enabled }
		~ Enable SubPart furniture { Enabled }
		~ Enable SubPart lamp posts { Enabled }
		~ Enable SubPart lanterns { Enabled }
		~ Enable SubPart lightbulbs { Enabled }
		~ Enable SubPart neon sign { Enabled }
		~ Enable SubPart slopes { Enabled }
		~ Enable SubPart wall clock { Enabled }
		~ Enable SubPart wallpaper { Enabled }
	= Grim Industry { Loaded }
		~ Enable SubPart bridges { Enabled }
		~ Enable SubPart chunk loader { Enabled }
		~ Enable SubPart conveyor { Enabled }
		~ Enable SubPart decoration { Enabled }
		~ Enable SubPart doors { Enabled }
		~ Enable SubPart elemental blocks { Enabled }
		~ Enable SubPart extruder { Enabled }
		~ Enable SubPart fans { Enabled }
		~ Enable SubPart gates { Enabled }
		~ Enable SubPart gravity { Enabled }
		~ Enable SubPart hlights { Enabled }
		~ Enable SubPart ice maker { Enabled }
		~ Enable SubPart machines { Enabled }
		~ Enable SubPart metal works { Enabled }
		~ Enable SubPart nuclear { Enabled }
		~ Enable SubPart rways { Enabled }
		~ Enable SubPart sensors { Enabled }
		~ Enable SubPart shaped charges { Disabled }
		~ Enable SubPart spikes { Enabled }
		~ Enable SubPart steel { Enabled }
		~ Enable SubPart storage { Enabled }
		~ Enable SubPart torches { Enabled }
		~ Enable SubPart workbench upgrades { Enabled }
	= Grim Tools { Loaded }
		~ Enable SubPart backpacks { Enabled }
		~ Enable SubPart black diamond { Enabled }
		~ Enable SubPart boomerangs { Enabled }
		~ Enable SubPart buckets { Enabled }
		~ Enable SubPart chicken suit { Enabled }
		~ Enable SubPart chisel { Enabled }
		~ Enable SubPart detonators { Enabled }
		~ Enable SubPart extinguisher { Enabled }
		~ Enable SubPart grenade launcher { Enabled }
		~ Enable SubPart hammers { Enabled }
		~ Enable SubPart knives { Enabled }
		~ Enable SubPart machetes { Enabled }
		~ Enable SubPart masks { Enabled }
		~ Enable SubPart multitools { Enabled }
		~ Enable SubPart pokeball { Enabled }
		~ Enable SubPart portable workbench { Enabled }
		~ Enable SubPart powerstaff { Enabled }
		~ Enable SubPart ray guns { Enabled }
		~ Enable SubPart slingshots { Enabled }
		~ Enable SubPart spears { Enabled }
		~ Enable SubPart staffs { Enabled }
		~ Enable SubPart ultimate fist { Enabled }
		~ Enable SubPart wands { Enabled }
	= Grim Util { Loaded }
		~ Enable SubPart auto item replacer { Disabled }
		~ Enable SubPart auto torch { Enabled }
		~ Enable SubPart chicken feathers { Enabled }
		~ Enable SubPart debug { Disabled }
		~ Enable SubPart double doors { Enabled }
		~ Enable SubPart frozen { Enabled }
		~ Enable SubPart fusrodah { Enabled }
		~ Enable SubPart graves { Enabled }
		~ Enable SubPart infinite lava { Disabled }
		~ Enable SubPart time { Enabled }
	= Grim World { Loaded }
		~ Enable SubPart 8-bit mobs { Enabled }
		~ Enable SubPart corruption { Disabled }
		~ Enable SubPart desert wells { Enabled }
		~ Enable SubPart flat bedrock { Enabled }
		~ Enable SubPart floating island world type { Disabled }
		~ Enable SubPart floating islands { Enabled }
		~ Enable SubPart fungus { Enabled }
		~ Enable SubPart glowstone seeds { Enabled }
		~ Enable SubPart gunpowder reeds { Enabled }
		~ Enable SubPart ice pixie { Enabled }
		~ Enable SubPart more people { Disabled }
		~ Enable SubPart randomite { Enabled }
		~ Enable SubPart ruins { Enabled }
		~ Enable SubPart treasure mobs { Enabled }
		~ Enable SubPart world gen expanded { Enabled }

	OptiFine Version: OptiFine_1.12.2_HD_U_C7
	Render Distance Chunks: 7
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.201.1151.1008
	OpenGlRenderer: AMD Radeon HD 5450
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 2

**Comment by 115kino** [comment]
Where did you download the mod?

**Comment by ItzDennisz** [comment]
hasnt this issue been fixed already?

**Comment by 115kino** [comment]
This issue has been fixed already. Just need to make sure he didn’t download the mod from unofficial sources like 9minecraft.

**Comment by 0Chris0** [comment]
Oh I downloaded ot from 9minecraft😓
But Curse is functional, right?

**Comment by 115kino** [comment]
Yes. Make sure to download Aether Legacy on Curse. This is the official site where you can get the most updated versions. 9Minecraft is an unofficial source and usually doesn’t have the most updated version of Aether Legacy. https://minecraft.curseforge.com/projects/aether-legacy
