### ISSUE TITLE
crash when starting up

### ISSUE THREAD

**Issue by Velocihater** [Modding-Legacy/Aether-Legacy#325]
**Aether Legacy Version(s) Affected**:
v3.1

**Forge version**: 

2739 1.12.2
**Extra Mods**: 
  | State | ID                                | Version                     | Source                                             | Signature                                |
       |:----- |:--------------------------------- |:--------------------------- |:-------------------------------------------------- |:---------------------------------------- |
       | UC    | minecraft                         | 1.12.2                      | minecraft.jar                                      | None                                     |
       | UC    | mcp                               | 9.42                        | minecraft.jar                                      | None                                     |
       | UC    | FML                               | 8.0.99.99                   | forge-1.12.2-14.23.4.2739.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UC    | forge                             | 14.23.4.2739                | forge-1.12.2-14.23.4.2739.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UC    | ivtoolkit                         | 1.3.3-1.12                  | minecraft.jar                                      | None                                     |
       | UC    | micdoodlecore                     |                             | minecraft.jar                                      | None                                     |
       | UC    | lesslag                           | 1.0                         | minecraft.jar                                      | None                                     |
       | UC    | foamfixcore                       | 7.7.4                       | minecraft.jar                                      | None                                     |
       | UC    | techguns_core                     | 1.12.2-1.0                  | minecraft.jar                                      | None                                     |
       | UC    | movillages                        | 1.5.4                       | [1.12]MoVillages-1.5.4.jar                         | None                                     |
       | UC    | jei                               | 4.11.0.202                  | jei_1.12.2-4.11.0.202.jar                          | None                                     |
       | UC    | abyssalcraft                      | 1.9.4.10                    | AbyssalCraft-1.12.2-1.9.4.10.jar                   | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | UC    | acheads                           | 2.0.3                       | AbyssalCraft Heads-1.12.2-2.0.3.jar                | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | UC    | biomesoplenty                     | 7.0.1.2384                  | BiomesOPlenty-1.12.2-7.0.1.2384-universal.jar      | None                                     |
       | UC    | redstoneflux                      | 2.0.2                       | RedstoneFlux-1.12-2.0.2.3-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | cofhcore                          | 4.5.3                       | CoFHCore-1.12.2-4.5.3.20-universal.jar             | None                                     |
       | UC    | boptools                          | 0.0.3                       | boptools-1.12-0.0.3.0.jar                          | None                                     |
       | UC    | endercore                         | 1.12.2-0.5.35               | EnderCore-1.12.2-0.5.35.jar                        | None                                     |
       | UC    | codechickenlib                    | 3.2.0.345                   | CodeChickenLib-1.12.2-3.2.0.345-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UC    | brandonscore                      | 2.4.3                       | BrandonsCore-1.12.2-2.4.3.168-universal.jar        | None                                     |
       | UC    | cofhworld                         | 1.2.0                       | CoFHWorld-1.12.2-1.2.0.5-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | thermalfoundation                 | 2.5.0                       | ThermalFoundation-1.12.2-2.5.0.19-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | draconicevolution                 | 2.3.12                      | Draconic-Evolution-1.12.2-2.3.12.297-universal.jar | None                                     |
       | UC    | thermalexpansion                  | 5.5.0                       | ThermalExpansion-1.12.2-5.5.0.29-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | enderio                           | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UC    | enderiointegrationtic             | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UC    | mantle                            | 1.12-1.3.2.24               | Mantle-1.12-1.3.2.24.jar                           | None                                     |
       | UC    | tconstruct                        | 1.12.2-2.10.1.87            | TConstruct-1.12.2-2.10.1.87.jar                    | None                                     |
       | UC    | acintegration                     | 1.6.5                       | AbyssalCraft Integration-1.12.2-1.6.5.jar          | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | UC    | actuallyadditions                 | 1.12.2-r137                 | ActuallyAdditions-1.12.2-r137.jar                  | None                                     |
       | UC    | advancedcombat                    | 1.1.2                       | advancedcombat-1.1.2-[1.12].jar                    | None                                     |
       | UC    | aether_legacy                     | 1.12.2-v3.1                 | aether_legacy-v3.1.jar                             | None                                     |
       | U     | aether_legacy_addon               | 1.12.2-v1.0                 | aether_legacy_addon_1.12.2-v1.0.jar                | None                                     |
       | U     | aiimprovements                    | 0.0.1.3                     | AIImprovements-1.12-0.0.1b3.jar                    | None                                     |
       | U     | aquaticarmors                     | 1.0                         | aquaticarmors-1.0.1.jar                            | None                                     |
       | U     | ichunutil                         | 7.1.4                       | iChunUtil-1.12.2-7.1.4.jar                         | None                                     |
       | U     | backtools                         | 7.0.0                       | BackTools-1.12.2-7.0.0.jar                         | None                                     |
       | U     | betteradvancements                | 0.0.5.17                    | BetterAdvancements-1.12.2-0.0.5.17.jar             | None                                     |
       | U     | bibliocraft                       | 2.4.5                       | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
       | U     | blockarmor                        | 2.4.11                      | BlockArmor-1.12.2-2.4.11.jar                       | None                                     |
       | U     | borntobe                          | @VERSION@                   | borntobe-1.12.2-1.0.jar                            | None                                     |
       | U     | bullseye                          | 3.0.6                       | Bullseye-1.12.2-3.0.6.jar                          | None                                     |
       | U     | carbonado                         | 1.4.7                       | carbonado-1.4.7-mc1.12.x.jar                       | None                                     |
       | U     | cavern                            | 2.1.8                       | Cavern_1.12.2-v2.1.8.jar                           | None                                     |
       | U     | ceanimals                         | 1.4.1                       | ceanimals-1.12.2-1.4.1.jar                         | None                                     |
       | U     | chancecubes                       | 1.12.2-3.2.1.224            | ChanceCubes-1.12.2-3.2.1.224.jar                   | None                                     |
       | U     | chunkpregenerator                 | 1.8                         | Chunk Pregenerator V1.12-1.8.1.jar                 | None                                     |
       | U     | lagremoval                        | 1.0                         | clearlag-1.0.jar                                   | None                                     |
       | U     | conarm                            | 1.0.2                       | conarm-1.12.2-1.0.2.jar                            | None                                     |
       | U     | cns                               | 1.0                         | CraftingNetherStar 1.12.1 -1.1.jar                 | None                                     |
       | U     | cw                                | 1.0.2                       | creature_whisperer_1.0.2.jar                       | None                                     |
       | U     | customspawner                     | 3.11.4                      | CustomMobSpawner-3.11.4.jar                        | None                                     |
       | U     | cxlibrary                         | 1.6.1                       | cxlibrary-1.12.1-1.6.1.jar                         | None                                     |
       | U     | dailies                           | 1.12.2-6                    | dailies-1.12.2-6.jar                               | None                                     |
       | U     | defiledlands                      | 1.3.0                       | defiledlands-1.12.2-1.3.0.jar                      | None                                     |
       | U     | dldungeonsjdg                     | 1.11.1                      | DoomlikeDungeons-1.11.1-MC1.12.2.jar               | None                                     |
       | U     | llibrary                          | 1.7.14                      | llibrary-1.7.14-1.12.2.jar                         | None                                     |
       | U     | dragonmounts                      | 1.12-1.4.4                  | DragonMounts-1.12-1.4.4.jar                        | None                                     |
       | U     | mocreatures                       | 12.0.4                      | DrZharks MoCreatures Mod-12.0.4.jar                | None                                     |
       | U     | durabilityviewer                  | 1.4                         | DurabilityViewer-1.12-forge14.21.1.2387-1.4.jar    | None                                     |
       | U     | eleccore                          | 1.8.434                     | ElecCore-1.12.2-1.8.434.jar                        | None                                     |
       | U     | elementalcreepers                 | v4.3.3.g5616356             | ElementalCreepers-v4.3.3.g5616356.jar              | None                                     |
       | U     | mcjtylib_ng                       | 3.0.3                       | mcjtylib-1.12-3.0.3.jar                            | None                                     |
       | U     | elementaldimensions               | 0.3.0                       | elementaldimensions-1.12-0.3.0.jar                 | None                                     |
       | U     | endercompass                      | 1.2.6.1                     | EnderCompass-1.12-1.2.6.1.jar                      | None                                     |
       | U     | enderiobase                       | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | U     | enderioconduits                   | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | U     | enderioconduitsappliedenergistics | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | U     | enderioconduitsopencomputers      | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | U     | enderioconduitsrefinedstorage     | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | U     | enderiointegrationforestry        | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | U     | enderiointegrationticlate         | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | U     | enderiomachines                   | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | U     | enderiopowertools                 | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | U     | enderzoo                          | 1.12.1-1.4.0.49             | EnderZoo-1.12.1-1.4.0.49.jar                       | None                                     |
       | U     | endreborn                         | 0.1.9                       | EndReborn [0.1.9].jar                              | None                                     |
       | U     | epicsiegemod                      | 13.162                      | EpicSiegeMod-13.162.jar                            | None                                     |
       | U     | erebus                            | 1.0.22                      | Erebus-1.0.22.jar                                  | None                                     |
       | U     | galacticraftcore                  | 4.0.1.181                   | GalacticraftCore-1.12.2-4.0.1.181.jar              | None                                     |
       | U     | galacticraftplanets               | 4.0.1.181                   | Galacticraft-Planets-1.12.2-4.0.1.181.jar          | None                                     |
       | U     | mjrlegendslib                     | 1.12.2-1.1.4                | MJRLegendsLib-1.12.2-1.1.4.jar                     | None                                     |
       | U     | extraplanets                      | 1.12.2-0.4.0                | ExtraPlanets-1.12.2-0.4.0.jar                      | None                                     |
       | U     | foamfix                           | 0.9.9.1-1.12.2              | foamfix-0.9.9.1-1.12.2-anarchy.jar                 | None                                     |
       | U     | forgelin                          | 1.7.4                       | Forgelin-1.7.4.jar                                 | None                                     |
       | U     | friendlyfire                      | 1.5.8                       | FriendlyFire-1.12.2-1.5.8.jar                      | None                                     |
       | U     | fw                                | 1.6.0                       | FullscreenWindowed-1.12-1.6.0.jar                  | None                                     |
       | U     | funtnt                            | 1.12.2.0                    | funtnt-1.12.2.0.jar                                | None                                     |
       | U     | galaxite                          | 1.0.6                       | galaxite-1.0.6-mc1.12.x.jar                        | None                                     |
       | U     | gargoyles                         | 1                           | Gargoyles mod 1.12.2 patch 1.jar                   | None                                     |
       | U     | ironman                           | Beta-1.12.2-1.2.1           | IronMan-Beta-1.12.2-1.2.1.jar                      | None                                     |
       | U     | speedsterheroes                   | 1.12.2-2.0.4                | SpeedsterHeroes-1.12.2-2.0.4.jar                   | None                                     |
       | U     | lucraftcore                       | 1.12.2-2.2.2                | LucraftCore-1.12.2-2.2.2.jar                       | None                                     |
       | U     | heroesexpansion                   | 1.12.2-1.1.1                | HeroesExpansion-1.12.2-1.1.1.jar                   | None                                     |
       | U     | icbmclassic                       | 1.12.2-3.0.0.29             | ICBM-classic-1.12.2-3.0.0b29.jar                   | None                                     |
       | U     | iceandfire                        | 1.5.2                       | iceandfire-1.5.2.jar                               | None                                     |
       | U     | inventorytweaks                   | 1.63+release.109.220f184    | InventoryTweaks-1.63.jar                           | None                                     |
       | U     | ironchest                         | 1.12.2-7.0.40.824           | ironchest-1.12.2-7.0.40.824.jar                    | None                                     |
       | U     | journeymap                        | 1.12.2-5.5.2                | journeymap-1.12.2-5.5.2.jar                        | None                                     |
       | U     | jurassicraft                      | 2.1.9                       | JurassiCraft-1.12.2-2.1.9.jar                      | None                                     |
       | U     | jeid                              | 1.0.1-14                    | JustEnoughIDs-1.0.1-14.jar                         | None                                     |
       | U     | jeresources                       | 0.8.5.27                    | JustEnoughResources-1.12.2-0.8.5.27.jar            | None                                     |
       | U     | lcrdrfs                           | 2.0.0                       | LaserCreeperRobotDinoRidersFromSpace-2.0.0.jar     | None                                     |
       | U     | lycanitesmobs                     | 1.20.3.1 - MC 1.12.2        | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar        | None                                     |
       | U     | arcticmobs                        | 1.20.3.1 - MC 1.12.2        | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar        | None                                     |
       | U     | demonmobs                         | 1.20.3.1 - MC 1.12.2        | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar        | None                                     |
       | U     | desertmobs                        | 1.20.3.1 - MC 1.12.2        | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar        | None                                     |
       | U     | elementalmobs                     | 1.20.3.1 - MC 1.12.2        | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar        | None                                     |
       | U     | forestmobs                        | 1.20.3.1 - MC 1.12.2        | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar        | None                                     |
       | U     | freshwatermobs                    | 1.20.3.1 - MC 1.12.2        | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar        | None                                     |
       | U     | infernomobs                       | 1.20.3.1 - MC 1.12.2        | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar        | None                                     |
       | U     | junglemobs                        | 1.20.3.1 - MC 1.12.2        | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar        | None                                     |
       | U     | mountainmobs                      | 1.20.3.1 - MC 1.12.2        | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar        | None                                     |
       | U     | plainsmobs                        | 1.20.3.1 - MC 1.12.2        | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar        | None                                     |
       | U     | saltwatermobs                     | 1.20.3.1 - MC 1.12.2        | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar        | None                                     |
       | U     | shadowmobs                        | 1.20.3.1 - MC 1.12.2        | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar        | None                                     |
       | U     | swampmobs                         | 1.20.3.1 - MC 1.12.2        | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar        | None                                     |
       | U     | overlord                          | 2.4.10                      | Overlord-1.12.2-2.4.10.jar                         | None                                     |
       | U     | mechsoldiers                      | 1.1.6                       | MechSoldiers-1.12.2-1.1.6.jar                      | None                                     |
       | U     | melongolem                        | 1.1.1                       | MelonMod-1.12-1.1.1.jar                            | None                                     |
       | U     | minecolonies                      | 1.12.2-0.9.1-RELEASE        | minecolonies-1.12.2-0.9.1-RELEASE-universal.jar    | None                                     |
       | U     | minetogether                      | unspecified                 | minetogether-1.10.2-2.0.3.jar                      | None                                     |
       | U     | minetogetherserver                | unspecified                 | minetogether-1.10.2-2.0.3.jar                      | None                                     |
       | U     | minions                           | 2.0.3                       | Minions-1.12.2.jar                                 | None                                     |
       | U     | moarboats                         | 2.1.0.2                     | moarboats-1.12.2-2.1.0.2.jar                       | None                                     |
       | U     | moartinkers                       | 0.6.0                       | moartinkers-0.6.0.jar                              | None                                     |
       | U     | modnametooltip                    | 1.10.0                      | modnametooltip_1.12.2-1.10.0.jar                   | None                                     |
       | U     | zawa                              | 1.12.2-1.3.2                | zawa - 1.3.2 (1.12.2).jar                          | None                                     |
       | U     | moon-core                         | 7.0                         | moon-core 7.0 (1.12).jar                           | None                                     |
       | U     | moreplanets                       | 2.0.15                      | More-Planets-1.12.2-2.0.15-GC181.jar               | None                                     |
       | U     | morefurnaces                      | 1.10.5                      | MoreFurnaces-1.12.2-1.10.5.jar                     | None                                     |
       | U     | moreplanetsextras                 | 1.12.2-1.0                  | MorePlanetsExtras-1.12.2-1.0.jar                   | None                                     |
       | U     | mousetweaks                       | 2.8                         | MouseTweaks-2.8-mc1.12.1.jar                       | None                                     |
       | U     | mowziesmobs                       | 1.4.2                       | mowziesmobs-1.4.2.jar                              | None                                     |
       | U     | naturescompass                    | 1.5.1                       | NaturesCompass-1.12.2-1.5.1.jar                    | None                                     |
       | U     | nex                               | 2.1.14.15                   | NetherEx-1.12-2.1.14.15.jar                        | None                                     |
       | U     | recipehandler                     | 0.11                        | NoMoreRecipeConflict-0.11(1.12.2).jar              | None                                     |
       | U     | neid                              | 1.5.4.2                     | NotEnoughIDs-1.5.4.2.jar                           | None                                     |
       | U     | overpoweredarmorbar               | 0.2.1                       | overpoweredarmorbar-1.12.2-0.2.1.jar               | None                                     |
       | U     | placebo                           | 1.4.0                       | Placebo-1.12.2-1.4.0.jar                           | None                                     |
       | U     | primitivemobs                     | 1.1.6                       | primitivemobs-1.1.6_beta.jar                       | None                                     |
       | U     | raiders                           | 3.0.6                       | raiders-1.12.2-3.0.6.jar                           | None                                     |
       | U     | randomthings                      | 4.1.9                       | RandomThings-MC1.12.2-4.1.9.jar                    | None                                     |
       | U     | reccomplex                        | 1.4.7                       | RecurrentComplex-1.4.7.jar                         | None                                     |
       | U     | redstonearsenal                   | 2.5.1                       | RedstoneArsenal-1.12.2-2.5.1.13-universal.jar      | None                                     |
       | U     | redstonefluxarsenal               | 1.2.1                       | RedstoneFluxArsenal-1.12-1.2.1.jar                 | None                                     |
       | U     | reforged                          | 0.7.5                       | Reforged-0.7.5-1.12+.jar                           | None                                     |
       | U     | roguelike                         | 1.8.0                       | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
       | U     | satako                            | 2.17                        | Satako_1.12-2.17.jar                               | None                                     |
       | U     | jukebox                           | 1.12.2-0.0.1.20180419095007 | SBM-JukeBox-1.12.2-0.0.1.jar                       | None                                     |
       | U     | merpig                            | 1.12.2-0.0.1.20180406032656 | SBM-Merpig-1.12.2-0.0.1b20180406032702.jar         | None                                     |
       | U     | scp                               | 1.2                         | SCP_Lockdown-1.12.2-1.2-hotfix.jar                 | None                                     |
       | U     | spartanshields                    | 1.4.1                       | SpartanShields-1.12.2-1.4.1.jar                    | None                                     |
       | U     | spartanweaponry                   | beta 1.1.2                  | SpartanWeaponry-1.12.2-beta-1.1.2.jar              | None                                     |
       | U     | spectrite                         | 1.6.6                       | spectrite-1.6.6.jar                                | None                                     |
       | U     | supertnt                          | 1.0.0                       | SuperTNT-1.12.2-1.0.0.jar                          | None                                     |
       | U     | tammodized                        | 0.15.5                      | TamModized-1.12.1-0.15.5.jar                       | None                                     |
       | U     | techguns                          | 2.0.1.1                     | techguns-1.12.2-2.0.1.1.jar                        | None                                     |
       | U     | thebetweenlands                   | 3.3.10                      | TheBetweenlands-3.3.10-universal.jar               | None                                     |
       | U     | thermaldynamics                   | 2.5.1                       | ThermalDynamics-1.12.2-2.5.1.14-universal.jar      | None                                     |
       | U     | thermalinnovation                 | 0.3.0                       | ThermalInnovation-1.12.2-0.3.0.7-universal.jar     | None                                     |
       | U     | tinker_io                         | release 2.6.1               | tinker_io-1.12.2-release 2.6.1.jar                 | None                                     |
       | U     | tinkersaddons                     | 1.0.7                       | Tinkers' Addons-1.12.1-1.0.7.jar                   | None                                     |
       | U     | tinkersaether                     | 1.1.5                       | tinkersaether-1.1.5.jar                            | None                                     |
       | U     | tcomplement                       | ${version}                  | TinkersComplement-1.12.2-0.2.3b.jar                | None                                     |
       | U     | tinkersjei                        | 1.0                         | tinkersjei-1.0.jar                                 | None                                     |
       | U     | togetherforever                   | 1.0.2                       | togetherforever-1.12.2-1.0.10-17.jar               | None                                     |
       | U     | torohealthmod                     | 1.12.2-11                   | torohealth-1.12.2-11.jar                           | None                                     |
       | U     | toroquest                         | 1.12.2-5.2                  | toroquest-1.12.2-5.2.jar                           | None                                     |
       | U     | totemexpansion                    | 1.2.2                       | totemexpansion-1.2.2-1.12.2.jar                    | None                                     |
       | U     | treechopper                       | 1.2.4                       | TreeChopper-1.12.2-1.2.4.jar                       | None                                     |
       | U     | twilightforest                    | 3.7.424                     | twilightforest-1.12.2-3.7.424-universal.jar        | None                                     |
       | U     | vanillafix                        | 1.0.9-97                    | VanillaFix-1.0.9-97.jar                            | None                                     |
       | U     | voidcraft                         | 0.26.10                     | VoidCraft-1.12-0.26.10.jar                         | None                                     |
       | U     | vulcanite                         | 1.3.10                      | vulcanite-1.3.10-mc1.12.x.jar                      | None                                     |
       | U     | thejungle                         | 1.1024.1222                 | Welcome To The Jungle-1.1024.1222.jar              | None                                     |
       | U     | wolfarmor                         | 2.2.3.6                     | wolfarmor-1.12.2-2.2.3.1798-universal.jar          | None                                     |
       | U     | worldedit                         | 6.1.8                       | worldedit-forge-mc1.12-6.1.8-dist.jar              | None                                     |
       | U     | xplosives                         | 1.1                         | xplosives-1.1.jar                                  | None                                     |

**Issue:**
Crash on start up

**How to reproduce:**
Simpy start up the game

**Crash log:**
java.lang.NoClassDefFoundError: Lcom/legacy/aether/CommonProxy;
    at java.lang.Class.getDeclaredFields0(Native Method)
    at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
    at java.lang.Class.getDeclaredField(Class.java:2068)
    at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:70)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:601)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:226)
    at net.minecraft.client.Minecraft.init(Minecraft.java:466)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3927)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.legacy.aether.CommonProxy
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 40 more
Caused by: java.lang.NullPointerException

**Comment by Lachney** [comment]
You have the  | U | aether_legacy_addon | 1.12.2-v1.0 | aether_legacy_addon_1.12.2-v1.0.jar | None |


Right now there is an issue w/ that mod and the author is looking into it.  Temp disable this mod if you want to launch properly.
